### ISSUE TITLE
Starlarkify and open-source DexArchiveAspect

### ISSUE THREAD

**Issue by ted-xie** [bazelbuild/rules_android#103]
[DexArchiveAspect](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/android/DexArchiveAspect.java;l=86?q=dexarchiveaspect), part of the android_binary compilation process, is still implemented in Java and baked into native.android_binary. This issue tracks its Starlarkification and open source release.

**Comment by ahumesky** [comment]
Starlarkified and open sourced with https://github.com/bazelbuild/rules_android/commit/035371cc08e79d2544f04b8e3811904808aabcd1
