### ISSUE TITLE
Starlarkify APK packaging steps in android_binary

### ISSUE THREAD

**Issue by ted-xie** [bazelbuild/rules_android#107]
[APK packaging](https://cs.opensource.google/bazel/bazel/+/refs/heads/master:src/main/java/com/google/devtools/build/lib/rules/android/ApkActionsBuilder.java;drc=f9f0806ec501093ba081115c0257c41b057c7b9e;l=38), which is one of the last steps in android_binary, is still handled by native.android_binary(). As part of the greater Starlarkification effort, this step should be migrated to Starlark.

**Comment by ahumesky** [comment]
This is migrated to Starlark
