### ISSUE TITLE
Open source NeverlinkAspect (android_binary)

### ISSUE THREAD

**Issue by jylinv0** [bazelbuild/rules_android#110]
[NeverlinkAspect](https://github.com/bazelbuild/bazel/blob/65cd8d9fac5c900b2df22288ad83acf207089e6e/src/main/java/com/google/devtools/build/lib/rules/android/AndroidRuleClasses.java#L475) is used in native `android_library` and `android_binary`. As part of effort to open source both rules, this aspect needs to be written in Starlark and open sourced.

**Comment by ahumesky** [comment]
This has been open sourced: https://github.com/bazelbuild/rules_android/commit/d7a357f2e7daa4c9774becf60990f5e070e8402e
