### ISSUE TITLE
Migrate deployInfo to Starlark implementation

### ISSUE THREAD

**Issue by ted-xie** [bazelbuild/rules_android#113]
native.android_binary()'s [deployInfo](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/android/AndroidBinary.java;l=769?q=f:androidbinary%20deploy.*info) enables Bazel to interface with IDEs (specifically with the ASwB plugin). This should be migrated to Starlark to integrate better with the Starlark android_binary.

**Comment by ahumesky** [comment]
This is migrated to Starlark
