### ISSUE TITLE
Open source mobile-install

### ISSUE THREAD

**Issue by jin** [bazelbuild/rules_android#12]
mobile-install v2 is a Starlark rewrite of the native `mobile-install` command in Bazel. 

This is the tracking bug for the open sourcing of v2.

**Comment by ahumesky** [comment]
This is one of the next bodies of code to be open sourced

**Comment by ted-xie** [comment]
Mobile-Install v3 is ready for beta testing for Linux users. I am actively working towards verifying Mac functionality. Details can be found in [this doc](https://docs.google.com/document/d/1PAANxcHNnKMI6k5hdKIlFyx_rHaV7WkJjDi15XrZSnM/edit), which will be updated as the work progresses.

**Comment by ted-xie** [comment]
The mobile-install beta testing doc has been updated with new information about Mac and bzlmod compatibility.

**Comment by ted-xie** [comment]
Closing this issue since the open sourcing effort has been completed.
