### ISSUE TITLE
android_sdk_repository isn't compatible with Bzlmod

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/rules_android#144]
The current Starlark implementation relies on native functions like [bind](https://github.com/bazelbuild/rules_android/blob/main/rules/android_sdk_repository/rule.bzl#L171) and [register_toolchains](https://github.com/bazelbuild/rules_android/blob/main/rules/android_sdk_repository/rule.bzl#L202) which are not supported in the Bzlmod `MODULE.bazel` file.

**Comment by keith** [comment]
this is mostly fixed by https://github.com/bazelbuild/rules_android/pull/147, for the bind uses we'll have to change bazel I believe

**Comment by meteorcloudy** [comment]
For avoiding bind usages, you can check https://bazel.build/external/migration#bind-targets, my guess is no Bazel change is required.

**Comment by katre** [comment]
Native Android rules depend on `//external` for a variety of things (mostly implicit dependencies on tools and the SDKs).

We should be able to remove these in the Starlark rules for the most part.

**Comment by meteorcloudy** [comment]
Probably here: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/rules/android/AndroidSdkRepositoryRule.java;l=38-45

**Comment by meteorcloudy** [comment]
And https://cs.opensource.google/bazel/bazel/+/master:src/tools/android/java/com/google/devtools/build/android/r8/BUILD;l=55

I believe even before starlarkfying the android build rules, we can just replace those labels to directly pointing to `@bazel_tools`

**Comment by katre** [comment]
The actual labels are in `@androidsdk`, unless the user names the repo something different, and not all projects even create the repo (which is why `//external:has_androidsdk` exists).

**Comment by ted-xie** [comment]
FWIW I am close to fixing this (finally!). There are two changes pending review internally, after which a follow-up CL will clean up all the binds. There will also be a small bazelrc change necessary to point the SDK away from bazel's implicit definition: `--android_sdk=@androidsdk//:sdk`.

**Comment by meteorcloudy** [comment]
Very exciting to hear that, thanks for your hard work! 

Do I understand correctly that if we want to remove all the binds from Bazel's WORKSPACE.bzlmod file, we'll have to build Bazel with Bazel@HEAD?

**Comment by ted-xie** [comment]
For Bazel itself, we'll delete the android_sdk_repository rule entirely closer to the Bazel 8 release, and when that happens, we can delete the binds too.
