### ISSUE TITLE
rules_android failing on Bazel CI

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_android#15]
https://buildkite.com/bazel/rules-android/builds?page=20
This project is red on Bazel CI since Aug 19, 2019.
Is there any plan to fix it?
```
(00:17:49) ERROR: /workdir/android/toolchains/emulator/BUILD:15:1: no such package '@androidsdk//': The repository '@androidsdk' could not be resolved and referenced by '//android/toolchains/emulator:emulator_default'
(00:17:49) ERROR: /workdir/android/toolchains/emulator/BUILD:15:1: no such package '@androidsdk//': The repository '@androidsdk' could not be resolved and referenced by '//android/toolchains/emulator:emulator_default'
```

**Comment by c-parsons** [comment]
This is still an issue. I'd advocate for removing rules_android from Bazel's buildkite verification flow

**Comment by meteorcloudy** [comment]
@jin WDYT? Should we remove it only from the downstream or this entire project from Bazel CI? What's the status of this repo?

**Comment by ted-xie** [comment]
@meteorcloudy can we close this (old) issue? rules_android has its own presubmit CI now and doesn't rely on being downstream from bazelbuild/bazel's CI.

**Comment by meteorcloudy** [comment]
Do you mean rules_android is not using Bazel CI at all? Do you still use https://buildkite.com/bazel/rules-android?

**Comment by ted-xie** [comment]
@kotlaja has fixed this.
