### ISSUE TITLE
Migrate to Bzlmod for managing external dependencies

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_android#159]
With future Bazel LTS versions, Bzlmod will become the default system for external dependencies management.

Please consider migrating all your external dependencies in WORKSPACE to MODULE.bazel

For more information, please check https://github.com/bazelbuild/bazel/issues/18958

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3352#018af627-f96d-4305-bb29-8af240ab7f95
Looks like only two tests failing:
```
//src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/apidescriptors:ExtractApiDescriptorsCommandTest FAILED in 3 out of 3 in 0.4s
//src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdkdependenciesmanifest:GenerateSdkDependenciesManifestCommandTest FAILED in 3 out of 3 in 0.5s
```

**Comment by meteorcloudy** [comment]
We need to use the Java runfiles library at 
https://github.com/bazelbuild/rules_android/blob/5f969078a26aa472638b0c16f6c0e747dbb560f4/src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/apidescriptors/ExtractApiDescriptorsCommandTest.java#L39-L42

**Comment by ted-xie** [comment]
We're 100% on bzlmod now, closing this.
