### ISSUE TITLE
sandboxedsdktoolbox tests not compatible with bzlmod

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_android#170]
These tests are failing with `--enable_bzlmod`:

1. `//src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/apidescriptors:ExtractApiDescriptorsCommandTest`
2. `//src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/runtimeenabledsdkconfig:GenerateRuntimeEnabledSdkConfigCommandTest`
3. `//src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdkdependenciesmanifest:GenerateSdkDependenciesManifestCommandTest`

Sample error:
```
1) extractApiDescriptors_keepsAnnotatedClassesInDescriptors(com.google.devtools.build.android.sandboxedsdktoolbox.apidescriptors.ExtractApiDescriptorsCommandTest)
java.nio.file.NoSuchFileException: /usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/ddb4e20e0e2e6bca92f5deeef02ce168/sandbox/linux-sandbox/1388/execroot/_main/_tmp/06932dec88f8df1b669921cbbc492d44/junit4088211020903516955/output.jar
```

Probably cause is not using the correct runfiles library to find data files.

**Comment by katre** [comment]
@ahumesky This is probably also a runfiles problem

**Comment by ahumesky** [comment]
`//src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/apidescriptors:ExtractApiDescriptorsCommandTest` also failed to build for me:

```
src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/apidescriptors/ExtractApiDescriptorsCommandTest.java:55: error: [strict] Using type com.google.common.collect.ImmutableList from an indirect dependency (TOOL_INFO: "@@rules_jvm_external~4.5~maven~rules_android_maven//:com_google_guava_guava"). See command below **
    ImmutableList<String> outputJarEntryNames =
    ^
 ** Please add the following dependencies: 
  @@rules_jvm_external~4.5~maven~rules_android_maven//:com_google_guava_guava to //src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/apidescriptors:ExtractApiDescriptorsCommandTest 
```

with or without bzlmod -- did you fix fix this locally / separately?

**Comment by katre** [comment]
No, I didn't do anything for that. Very odd.

**Comment by ahumesky** [comment]
well, besides that strictdeps error, the same fix for https://github.com/bazelbuild/rules_android/issues/180 appears to fix these as well

**Comment by katre** [comment]
Please re-enable tests when you submit fixes.
