### ISSUE TITLE
aidl rust backend

### ISSUE THREAD

**Issue by geaden** [bazelbuild/rules_android#191]
I'm trying to achieve https://google.github.io/comprehensive-rust/android/aidl/interface.html but with bazel.

I need to specify rust backend, so that rust stubs were generated

**Comment by ahumesky** [comment]
It's unlikely that we'll add this directly to the android rules, but it might be possible to do this through a genrule or some additional starlark.

A basic example:

`WORKSPACE`:
```
android_sdk_repository(name = "androidsdk")
```

`BUILD`:
```
genrule(
  name = "aidl_rust",
  srcs = ["com/example/android/IRemoteService.aidl"],
  outs = ["com/example/android/IRemoteService.rs"],
  tools = ["@androidsdk//:aidl_binary"],
  cmd = "$(location @androidsdk//:aidl_binary) --lang=rust $< --out $(GENDIR)",
)
```

`com/example/android/IRemoteService.aidl`:
```
// IRemoteService.aidl
package com.example.android;

// Declare any non-default types here with import statements

/** Example service interface */
interface IRemoteService {
    /** Request the process ID of this service, to do evil things with it. */
    int getPid();

    /**
     * Demonstrates some basic types that you can use as parameters
     * and return values in AIDL.
     */
    void basicTypes(int anInt, long aLong, boolean aBoolean, float aFloat,
            double aDouble, String aString);
}
```

```
$ bazel build aidl_rust
INFO: Analyzed target //:aidl_rust (72 packages loaded, 331 targets configured).
INFO: Found 1 target...
Target //:aidl_rust up-to-date:
  bazel-bin/com/example/android/IRemoteService.rs
INFO: Elapsed time: 0.560s, Critical Path: 0.02s
INFO: 7 processes: 5 internal, 2 linux-sandbox.
INFO: Build completed successfully, 7 total actions
```


Some additional poking around:

This is where aidl_interface is implemented in Soong:

https://cs.android.com/android/platform/superproject/main/+/main:system/tools/aidl/build/aidl_interface.go;drc=5c3d46d304ce279646c9649d4c6a76f21b71cfbf

here's a bazel equivalent of aidl_interface in Android Platform:
https://cs.android.com/android/platform/superproject/main/+/main:build/bazel/rules/aidl/aidl_interface.bzl;l=95;drc=17861480bfd6af30fdf77c44b134664e03f164e7

but notably rust support is not there: 
https://cs.android.com/android/platform/superproject/main/+/main:build/bazel/rules/aidl/aidl_interface.bzl;l=22;drc=17861480bfd6af30fdf77c44b134664e03f164e7

this appears to be the invocation of aidl for rust:
https://cs.android.com/android/platform/superproject/main/+/main:system/tools/aidl/build/aidl_gen_rule.go;l=65;drc=5c3d46d304ce279646c9649d4c6a76f21b71cfbf

There's this additional "aidl rust glue":
https://cs.android.com/android/platform/superproject/main/+/main:system/tools/aidl/build/aidl_rust_glue.py;drc=d8a838aec6662e409106ddc6ca128e1bd3b3b8c9

some comments about it here:
https://cs.android.com/android/platform/superproject/main/+/main:system/tools/aidl/build/aidl_rust_source_provider.go;l=69-76;drc=bee38ebf2b27015f05e5e34d21fc7e4b33a10333

**Comment by geaden** [comment]
@ahumesky Thanks! I'll give it a try

**Comment by geaden** [comment]
I've given it a try and it works perfect! One thing to notice:

`$(GENDIR)` worked only if I put my `genrule` in the workspace root `BUILD.bazel`.

For other cases (if my `*.aidl` resides in let's say `//src/birthdayservice/aidl/com/example/birthdayservice/IBirthdayService.aidl`) I used `$(RULEDIR)` instead.

I'm closing the issue. Thanks again @ahumesky for the detailed response!
