### ISSUE TITLE
Default debug_keystore is missing

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/rules_android#196]
The `debug_keystore` doesn't seem to be checked in which causes `rules_android` to fail. Ex: https://github.com/bazelbuild/rules_android/tree/main/tools/android

Error:
```
(12:47:51) ERROR: /private/var/tmp/_bazel_blee/499a001013731d09bffd82f8601a3161/external/rules_android/tools/android/BUILD: no such target '@rules_android//tools/android:debug_keystore': target 'debug_keystore' not declared in package 'tools/android' defined by /private/var/tmp/_bazel_blee/499a001013731d09bffd82f8601a3161/external/rules_android/tools/android/BUILD (Tip: use `query "@rules_android//tools
/android:*"` to see all the targets in that package)
```

**Comment by Bencodes** [comment]
There might already be one defined in the `bazel_tools` that can be aliased https://github.com/bazelbuild/bazel/blob/85855fcbaecda5bed87ccaac7acd5d016027ef0a/tools/android/BUILD.tools#L401

**Comment by ahumesky** [comment]
Addressed by https://github.com/bazelbuild/rules_android/pull/197
