### ISSUE TITLE
Bazel should support D8 Desugaring

### ISSUE THREAD

**Issue by jongerrish** [bazelbuild/rules_android#20]
## Problem

For our build we have ~1700 `Desugar` actions, it would be great if we could use D8's built in desugaring functionality.

## Obstacles

* Disabling desugaring using the flag --nodesugar_for_android forces android_library targets to build with source + target Java version = 6.
* The version of D8 that Bazel uses is actually `D8Compat` which explicitly disables D8 desugaring.
* D8Compat is designed to be API compatible with the old DX tool and as such the command line parameters Bazel passes are not compatible with D8 proper. For Android build tools 29 it doesn't currently support reading from a params file, although this appears to be supported on master in the Android tree.
* D8 when desugaring does not tolerate duplicate classes in its classpath, projects will need to deal with this individually.

## Work required

* Add new build tool target in Bazel for D8 proper (vs D8Compat target)
* Add new flag to Bazel --use_d8_desugar which
  * Does not affect source + target Java version
    * Controls a Factory? that produces
    * CompatD8 or D8 Proper executable.
    * Command line parameters for the appropriate DX tool

## Further work
* Support a mechanism to disable desugaring for some artifacts, e.g: `*_resource.jar` which do not require desugaring.

**Comment by jongerrish** [comment]
@ahumesky @jin @timpeut 

I'm working on implementing this in our Bazel for if you're interested in a contribution? :-)

**Comment by ahumesky** [comment]
D8-based desugaring (and dexing, for that matter) will be released in Bazel 6.0.0

**Comment by arunkumar9t2** [comment]
@ahumesky Thanks, we were able to import and verified d8 desugaring successfully. 

Is there a plan to merging dexing + desugar into a single action like Gradle does?

**Comment by ted-xie** [comment]
@arunkumar9t2 Glad that you were able to get D8 desugaring to work!

> Is there a plan to merge dexing + desugar into a single action like Gradle does?

Do you mean in relation with R8 integration?

**Comment by arunkumar9t2** [comment]
Yes, currently bazel uses saparate actions for dexing and desugaring, if both are merged into a single action since D8/R8 supports that then we could save on no of actions + cache output.
