### ISSUE TITLE
Mobile install v3 doesn't work with --start=debug

### ISSUE THREAD

**Issue by gottagofaster236** [bazelbuild/rules_android#225]
Steps to reproduce:
- macOS
- Follow the steps to setup the new mobile install from here: https://docs.google.com/document/d/1PAANxcHNnKMI6k5hdKIlFyx_rHaV7WkJjDi15XrZSnM/edit
- Run `bazel mobile-install @@//examples/basicapp/java/com/basicapp:basic_app --start=debug`
- Bazel prints the following in the logs: `ERROR: Unable to wait for debugger: exec: not started`

**Comment by ted-xie** [comment]
We merged your PR #226 as https://github.com/bazelbuild/rules_android/commit/06a033b15e05b4c56980c4a094b9f6ad19c11c13, which I think should fix this issue.
