### ISSUE TITLE
Migration path off android_common.multi_cpu_configuration

### ISSUE THREAD

**Issue by tomrenn** [bazelbuild/rules_android#294]
Android Studio has a `android_cc_binary` rule that builds a `cc_binary` in an Android configuration. This uses the `android_common.multi_cpu_configuration` natively built into Bazel. [Rule Source](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:bazel/android.bzl;l=50-59;drc=6fe0102b7faccb580df48550c47490ebdd1d19fe)

I tried migrating to rules_android, but am not sure how to migrate this usage. I tried using [`android_split_transition`](https://github.com/bazelbuild/rules_android/blob/bd6d0e3644cb6d7183280a2e01a644677f64430d/rules/android_split_transition.bzl#L109-L112) as the replacement transition, but when I compile the `android_cc_binary` targets, I now get build failures with the following error

```
ld.lld: error: unable to find library -lpthread
```

I found https://github.com/bazelbuild/rules_android_ndk/issues/5 which mentions the `-lpthread` issue. However, I was not having this problem before when using the native `android_common.multi_cpu_configuration`, and am not sure why I am now getting this compilation failure. Is there a different transition I should be using for these types of custom rules?

**Comment by ahumesky** [comment]
One difference between the native `android_common.multi_cpu_configuration` and the Starlark `android_split_transition` is that the native version still handled the legacy `--fat_apk_cpu` and related flags: https://github.com/bazelbuild/bazel/blob/24caa1d30a7cce01a61fcd70f6a65378bf9c261e/src/main/java/com/google/devtools/build/lib/rules/android/AndroidSplitTransition.java#L86-L88

while the Starlark version only handles `--android_platforms`:
https://github.com/bazelbuild/rules_android/blob/bd6d0e3644cb6d7183280a2e01a644677f64430d/rules/android_split_transition.bzl#L91-L97

Are you seeing this with `--fat_apk_cpu`, `--android_crosstool_top`, etc, or with `--android_platform`?

**Comment by tomrenn** [comment]
This is using `--android_platforms`, after upgrading to Bazel 7 we stopped using `--fat_apk_cpu` and `--android_crosstool_top`.

**Comment by tomrenn** [comment]
Using `bazel query 'deps(//mytarget)' --output=build` was useful to identify what dependency was adding `-lpthread`. It was protobuf adding `-lpthread` because it used crosstool_top for determining android. It used the following config_setting

```
config_setting(
    name = "android",
    values = {
        "crosstool_top": "//external:android/crosstool",
    },
)
```

If I modify the protobuf dependency to use `@platforms//os:android` instead it works :) We really need to update our project to be using a more recent version of protobuf

**Comment by ahumesky** [comment]
Thanks for getting back, glad you were able to get to the root cause
