### ISSUE TITLE
Clarify the plan for this repository

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/rules_android#3]
At this point, the rules_android repo is 8 months stale, and still is a simple pass-through to the native rules.  This is becoming a gating factor for migration, as lack of mac compability in instrumentation testing, inability to modify rules for local conditions, lack of an aar publishing rule (that can make a public, fat, shaded .aar for distribution) all of these are making it hard to move forward with bazel migration.

Please clarify some plans here, throw in a roadmap document that is current, file issues/projects for the work to be done, or in some way communicate to the users.

**Comment by 10-10-11** [comment]
Thanks for bringing this up. We will have a roadmap published within the next two weeks. The plan for this repository is to contain the Starlark version of the Android rule set. We're currently creating these Starlark rules, and it will still be some time before they're ready for an initial release.

Note though that the first release of the Starlark rules is intended to be 1:1 compatible with the native rules. After that we will address the missing features, e.g. Mac support for android_instrumentation_test, a better way to generate AAR's with its own new rule, the ability to generate Android App Bundle (AAB) and more.

**Comment by cgruber** [comment]
Ok.  I hear you.  I am somewhat concerned about "for some time now" as some of my earlier conversations with teams in Google indicated the possibility of January for early versions appearing externally, and some of these are adoption blockers for Square, at least "delayers".   If it's possible to publish earlier versions, even versions that aren't backwords-compatible with the native rules (but basically functional) versions into an early release branch, that would really help teams that are pushing hard towards Bazel adoption.  This would at least let such firms patch locally while tracking the progress, working towards removing those patches as the public ruleset evolves.

**Comment by cgruber** [comment]
I apologize - I should have prefaced the above anxious note with "OMG YES, THANK YOU!" because I genuinely am excited that there's ownership and progress emerging on some of these external rules projects.  Definitely exciting times.  Just also painful for those of us at the bleeding edge.  :)

**Comment by cgruber** [comment]
Any news here?  We're finding it hard to plan our migration at Square absent any data on what's being planned on your end.

**Comment by timpeut** [comment]
Thanks for your patience. We've been working through all filed issues (internal + external) and the previously published roadmaps to put together the [new roadmap for rules_android](https://github.com/bazelbuild/rules_android/blob/master/ROADMAP.md).
