### ISSUE TITLE
Checksum changed

### ISSUE THREAD

**Issue by rockwotj** [bazelbuild/rules_android#42]
We're getting some of these errors:

```
WARNING: Download from https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 7cb2b2e11aafe08b2ccb6eeb11f21f52c45e1ad1cdd0132ddf7bde8462bd9e20 but wanted cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806
```

Indeed verifying the sha for me on my macbook shows it has changed:

```
$ curl -sL https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip | shasum -a 256 -b
cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806 *-
```

**Comment by rockwotj** [comment]
Wait my computer is showing the old one... Huh

**Comment by arunkumar9t2** [comment]
Issue with Github which was reverted https://twitter.com/tgummerer/status/1488493440103030787

**Comment by ahumesky** [comment]
Github made a change that caused the zips to change, they've since rolled it back:
https://twitter.com/tgummerer/status/1488493440103030787

**Comment by notnarb** [comment]
I am seeing this exact same issue and I'm able to reproduce locally

```
[~/Downloads]
bhorsley$ export URL="https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip"
[~/Downloads]
bhorsley$ curl -sL $URL | sha256sum
cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806  -
[~/Downloads]
bhorsley@beehorse$ wget -O- $URL 2> /dev/null | sha256sum
7cb2b2e11aafe08b2ccb6eeb11f21f52c45e1ad1cdd0132ddf7bde8462bd9e20  -
```

both files are valid zip files and diffing the output with `xxd` I can see that the files are *extremely* similar but not identical.

---

I do not see the same issue when using an alternative URL: `https://github.com/bazelbuild/rules_android/archive/refs/tags/v0.1.1.zip`

**Comment by notnarb** [comment]
> Github made a change that caused the zips to change, they've since rolled it back:

Good find, thank you @ahumesky 

Per that thread:

> In general we don't guarantee that the checksums of zip downloads will stay the same, they do for downloads of releases though.

Given this should the README for this repo update the URL in its example to the release url rather than the download URL ?

Download URL: `https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip`
⬇️
Release URL: `https://github.com/bazelbuild/rules_android/archive/refs/tags/v0.1.1.zip`

**Comment by notnarb** [comment]
Actually there is already an open issue around this: #43 I'll resurface this suggestion there
