### ISSUE TITLE
Register NDK cc_toolchain as compatible with armv7

### ISSUE THREAD

**Issue by korDen** [bazelbuild/rules_android#44]
Starting with r17, Android no longer supports armeabi and instead compiles for armeabi-v7a. However, the toolchain is still registered as compatible with @platforms//cpu:arm and not @platforms//cpu:armv7. This results in toolchain not being found when targetting @platforms//cpu:armv7.

With --toolchain_resolution_debug, I see the following messages:

```
Type @bazel_tools//tools/cpp:toolchain_type: target platform //platforms:android_armv7: Rejected toolchain @androidndk//:arm-linux-androideabi-clang9.0.8-v7a-libcpp; mismatching values: arm
Type @bazel_tools//tools/cpp:toolchain_type: target platform //platforms:android_armv7: Rejected toolchain @local_config_cc//:cc-compiler-armeabi-v7a; mismatching values: arm
```

If possible, please register the toolchain as compatible with both @platforms//cpu:arm and @platforms//cpu:armv7, or provide a way to manually register the toolchain (in a generic way).

**Comment by ahumesky** [comment]
Feel free to reopen if this is still an issue
