### ISSUE TITLE
Error: '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'x86_64'

### ISSUE THREAD

**Issue by snazhmudinov** [bazelbuild/rules_android#47]
**Machine setup:**
macOS Monterey 12.4

Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

bazel version installed: `5.0.2`

I'm getting familiarized with Bazel, and trying to sync the small Android project in AS. 
Tutorial: https://bazel.build/tutorials/android-app

However, when I sync via AS UI, I get the following error:
```
Error:(48, 19) in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'x86_64'
```

I have no issue building and deploying the app via the terminal. 

Can someone please explain what I'm doing wrong? Thanks.

**Comment by snazhmudinov** [comment]
Downgrading/upgrading the bazel verion (via bazelisk) didn't work.

**Comment by arunkumar9t2** [comment]
It is possible AS is using different bazel version. Have you configured the bazel binary path in AS settings to use bazelisk?

**Comment by snazhmudinov** [comment]
i changed the bazel binary location to point to bazelisk, and it still gives the error :(
<img width="740" alt="Screen Shot 2022-07-17 at 10 42 23 AM" src="https://user-images.githubusercontent.com/10291949/179390867-4e18a2bc-6f44-40c4-a638-a7f6abd820da.png">

**Comment by arunkumar9t2** [comment]
Also worth running `clean ——expunge` to force toolchain resolution to run again.

**Comment by snazhmudinov** [comment]
Tried `clean --expunge` as well, it didn't really help. 
I'm fairly new to bazel, so at this point I wasn't sure how to proceed.

**Comment by ted-xie** [comment]
@snazhmudinov Still running into this issue?

**Comment by ted-xie** [comment]
If people are still running into this, I'd suggest upgrading Bazel versions to 6.0.0 or higher and seeing if the problem persists, and if you're using a newer NDK version, to use https://github.com/bazelbuild/rules_android_ndk in place of the native `android_ndk_repository`.

I think it would be prudent to close out this bug, since there seem to be multiple solutions/workarounds, and little activity in this thread. I'll circle back in a week and close this out if there are no objections.

**Comment by snazhmudinov** [comment]
Sorry for the silence. I will check with the new bazel version. Meanwhile I'm closing this issue. Thank you!
