### ISSUE TITLE
Release merge_feature_manifest.par

### ISSUE THREAD

**Issue by mauriciogg** [bazelbuild/rules_android#69]
Feature modules are broken due to merge_feature_manifest.par missing (https://github.com/bazelbuild/rules_android/blob/pre-alpha/rules/android_application/attrs.bzl#L62)

Can this be switched to the vanilla manifest merger? Other than having some special logic to insert `${MODULE_TITLE}` in the manifest I can't tell what else it might be doing.

**Comment by nkoroste** [comment]
@ahumesky @ted-xie what's special about that manifest merger? are you planning to upstream it?
