### ISSUE TITLE
Support building for other platforms

### ISSUE THREAD

**Issue by ted-xie** [bazelbuild/rules_android#72]
* M1 Mac
* x86 Mac
* x86 Windows

**Comment by nkoroste** [comment]
is M1 and x86 not supported already?

**Comment by ted-xie** [comment]
M1 and Mac x86 are now supported, technically, but Windows + any arch is not yet. I personally also don't consider any support "done" until we implement nightly regression tests making sure they don't regress, which we haven't yet.
