### ISSUE TITLE
Error during sync in Intellij IDEA 2019.1 and Android Studio 3.5

### ISSUE THREAD

**Issue by stepango** [bazelbuild/rules_android#9]
Having this error during sync in IDE

```
Error:/private/var/tmp/_bazel_stepango/46765f2287fb7d7cb567522e1d5568a9/external/androidsdk/BUILD.bazel:8:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on android_sdk rule @androidsdk//:sdk-29: 
```

No idea what this error message means and how to fix it. 

Anyway I could workaround this?

**Comment by jin** [comment]
What are your Bazel and Bazel plugin versions

**Comment by stepango** [comment]
Bazel version 0.28.1, Plugin version v2019.08.05.0.0

**Comment by jin** [comment]
Can you try adding `build --incompatible_depset_is_not_iterable` into your project's .bazelrc file? This may be https://github.com/bazelbuild/intellij/commit/b0787abe37fa59d65f1e71a1437900d24baee81f

**Comment by stepango** [comment]
Thanks a lot, will try.
