### ISSUE TITLE
Starlark dex implementation is not sharded

### ISSUE THREAD

**Issue by mauriciogg** [bazelbuild/rules_android#99]
The Starlark implementation for dexing differs from the native implementation in that it does not shard the dex files before merging. This introduces incremental performance regrission since dexmerge merges all dex files for all code changes.
In addition to the performance hit, a (probably unintended) side effect of dexfilesplitter is that it filters out duplicate classes which is not allowed. This was also previously possible due to the d8 [version being used](https://partnerissuetracker.corp.google.com/issues/240438146#comment7) . Ideally there should be no duplicate classes, but since this is not enforced, repos currently migrating to bazel could encounter this issue.

**Comment by timpeut** [comment]
The code you're referring to is still being migrated. We intend for the starlark implementation to generate the same actions as the native implementation.
